version: "3.8"
services:
  db:
    image: mysql:8.4
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - '3306:3306'
    environment: 
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: singlebcdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password1
    volumes: 
      - ./init-local-singlebc-db.sql:/docker-entrypoint-initdb.d/init.sql

  sbcpicker-api:
    image: node:23-alpine
    ports:
      - '48481:48481'
    environment: 
      PORT: 48481
      SQLHOST: db
      SQLDATABASE: singlebcdb
      SQLUSER: user
      SQLPASS: password1
      SQLPORT: 3306
    tty: true
    command: sh /infra/start-sbcpicker-api.sh
    volumes:
      - .:/infra
      - ./codebase/sbcpicker-nest:/kb
    depends_on:
      - db