version: "3.9"
services:
  db:
    image: mysql:8.4
    command: --mysql-native-password=ON
    restart: on-failure
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: password1
      MYSQL_DATABASE: singlebcdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password1
    volumes: 
      - ./init-local-singlebc-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', '$$MYSQL_USER', '-p$$MYSQL_ROOT_PASSWORD' ]
      start_period: 5s
      timeout: 10s
      retries: 20
  # cache:
  #   image: redis:6.2-alpine
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  #   volumes: 
  #     - ./cache:/data
  sbcpicker-api:
    image: node:23-alpine
    ports:
      - '48481:48481'
    environment: 
      PORT: 48481
      SQLHOST: db
      SQLDATABASE: singlebcdb
      SQLUSER: user
      SQLPASS: password1
      SQLPORT: 3306
    tty: true
    command: sh /infra/start-sbcpicker-api.sh
    volumes:
      - .:/infra
      - ./codebase/sbcpicker-nest:/kb
    depends_on:
      # cache:
      #   condition: service_started
      db:
        condition: service_healthy
  sbcpicker-web:
    image: node:18-alpine
    ports:
      - '3030:3030'
    environment: 
      ENVIRONMENT: development
      PORT: 3030
      APIHOST: sbcpicker-api
      APIPORT: 48481
    tty: true
    command: sh /infra/start-sbcpicker-frontend.sh
    volumes:
      - .:/infra
      - ./codebase/sbcpicker-frontend:/kb
    # depends_on:
    #   sbcpicker-api:
    #     condition: service_healthy